-- MailSentinel initial schema.
--
-- Deliberately plain SQL: identity columns and portable types only, so the same
-- migration runs on PostgreSQL and on H2 in PostgreSQL-compatibility mode.  The
-- test suite therefore exercises the real schema rather than an ORM-generated
-- approximation of it.

CREATE TABLE capture (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename            VARCHAR(512)  NOT NULL,
    sha256              VARCHAR(64),
    size_bytes          BIGINT        NOT NULL DEFAULT 0,
    format              VARCHAR(32),
    storage_path        VARCHAR(1024),
    packet_count        INTEGER,
    captured_at         TIMESTAMP,
    uploaded_at         TIMESTAMP,
    analysed_at         TIMESTAMP,
    status              VARCHAR(16)   NOT NULL,
    error_message       VARCHAR(4000),
    overall_grade       VARCHAR(4),
    overall_score       DOUBLE PRECISION,
    critical_count      INTEGER,
    high_count          INTEGER,
    medium_count        INTEGER,
    low_count           INTEGER,
    session_count       INTEGER,
    asset_count         INTEGER,
    credentials_exposed INTEGER,
    report_json         TEXT
);

CREATE INDEX idx_capture_sha256 ON capture (sha256);
CREATE INDEX idx_capture_status ON capture (status);

CREATE TABLE mail_session (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capture_id              BIGINT NOT NULL REFERENCES capture (id) ON DELETE CASCADE,
    session_key             VARCHAR(64),
    stream_index            INTEGER NOT NULL DEFAULT 0,
    first_frame             INTEGER NOT NULL DEFAULT 0,
    last_frame              INTEGER NOT NULL DEFAULT 0,
    protocol                VARCHAR(16),
    role                    VARCHAR(32),
    tls_mode                VARCHAR(16),
    client_ip               VARCHAR(64),
    client_port             INTEGER NOT NULL DEFAULT 0,
    server_ip               VARCHAR(64),
    server_port             INTEGER NOT NULL DEFAULT 0,
    server_name             VARCHAR(255),
    tls_version             VARCHAR(16),
    cipher_suite            VARCHAR(128),
    key_exchange            VARCHAR(16),
    key_exchange_bits       INTEGER,
    forward_secrecy         BOOLEAN,
    cert_visibility         VARCHAR(32),
    cert_subject            VARCHAR(255),
    cert_issuer             VARCHAR(255),
    cert_self_signed        BOOLEAN,
    cert_expired_at_capture BOOLEAN,
    chain_valid             BOOLEAN,
    starttls_offered        BOOLEAN,
    starttls_requested      BOOLEAN,
    starttls_accepted       BOOLEAN,
    capability_mangled      BOOLEAN,
    cleartext_auth          BOOLEAN,
    exposed_username        VARCHAR(255),
    grade                   VARCHAR(4),
    raw_score               DOUBLE PRECISION,
    capped_by               VARCHAR(32),
    trusted                 BOOLEAN,
    confidence              VARCHAR(16),
    ml_risk_class           VARCHAR(16),
    ml_risk_score           DOUBLE PRECISION,
    ml_anomaly              BOOLEAN,
    ml_explanation          VARCHAR(2000),
    ja3                     VARCHAR(64),
    ja4                     VARCHAR(64)
);

CREATE INDEX idx_session_capture ON mail_session (capture_id);
CREATE INDEX idx_session_grade   ON mail_session (grade);

CREATE TABLE finding (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT NOT NULL REFERENCES mail_session (id) ON DELETE CASCADE,
    rule_id         VARCHAR(32)  NOT NULL,
    severity        VARCHAR(16)  NOT NULL,
    title           VARCHAR(255) NOT NULL,
    standard        VARCHAR(512),
    remediation     VARCHAR(2000),
    detail          VARCHAR(2000),
    cap_grade       VARCHAR(4),
    evidence_frames VARCHAR(512)
);

CREATE INDEX idx_finding_session  ON finding (session_id);
CREATE INDEX idx_finding_rule     ON finding (rule_id);
CREATE INDEX idx_finding_severity ON finding (severity);

CREATE TABLE asset (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capture_id          BIGINT NOT NULL REFERENCES capture (id) ON DELETE CASCADE,
    asset_key           VARCHAR(255) NOT NULL,
    host                VARCHAR(255) NOT NULL,
    port                INTEGER NOT NULL DEFAULT 0,
    protocol            VARCHAR(16),
    role                VARCHAR(32),
    grade               VARCHAR(4),
    raw_score           DOUBLE PRECISION,
    capped_by           VARCHAR(32),
    trusted             BOOLEAN,
    session_count       INTEGER NOT NULL DEFAULT 0,
    distinct_clients    INTEGER NOT NULL DEFAULT 0,
    best_tls            VARCHAR(16),
    worst_tls           VARCHAR(16),
    version_spread      BOOLEAN,
    credentials_exposed BOOLEAN,
    exposure_score      DOUBLE PRECISION,
    ml_risk             DOUBLE PRECISION
);

CREATE INDEX idx_asset_capture  ON asset (capture_id);
CREATE INDEX idx_asset_exposure ON asset (exposure_score);
