CREATE TABLE investigation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE capture ADD COLUMN investigation_id BIGINT REFERENCES investigation(id);
ALTER TABLE capture ADD COLUMN source_capture_id BIGINT;
ALTER TABLE capture ADD COLUMN stage VARCHAR(64) DEFAULT 'QUEUED';
ALTER TABLE capture ADD COLUMN started_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX idx_capture_investigation ON capture(investigation_id);
CREATE TABLE remediation_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES investigation(id),
    finding_key VARCHAR(1000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    note VARCHAR(2000) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(investigation_id, finding_key)
);
