"""
Model training and honest evaluation.

Two models are produced:

  * a **RandomForest posture classifier**, trained on ground-truth server
    configuration labels — never on rule-engine output;
  * an **IsolationForest** baseline, refit per capture at prediction time on
    that capture's own sessions.

Evaluation uses ``GroupKFold`` with the configuration profile as the group, so
sessions generated by the same server never appear on both sides of a split.
A plain random split leaks and produces the fake 99% that makes a reviewer
stop believing the rest of the report.  Expect roughly 0.80–0.95 macro-F1
here; anything near 1.00 means a leak, not a triumph.

Per-class precision and recall are reported rather than a single accuracy
number, because aggregate accuracy hides exactly the failure that matters:
missing a critical.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from typing import Optional

import numpy as np
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GroupKFold

from ..features import FEATURE_NAMES
from .dataset import CLASSES, GeneratedDataset, generate

MODEL_VERSION = "1.0.0"
DEFAULT_ARTIFACT_DIR = os.path.join(os.path.dirname(__file__), "artifacts")


@dataclass
class TrainingReport:
    model_version: str = MODEL_VERSION
    n_samples: int = 0
    n_features: int = 0
    n_groups: int = 0
    classes: list[str] = field(default_factory=list)
    cv_folds: int = 0
    macro_f1_mean: float = 0.0
    macro_f1_std: float = 0.0
    accuracy_mean: float = 0.0
    per_class: dict = field(default_factory=dict)
    confusion: list[list[int]] = field(default_factory=list)
    by_certificate_visibility: dict = field(default_factory=dict)
    feature_importance: dict = field(default_factory=dict)
    tls13_masked_fraction: float = 0.0
    notes: list[str] = field(default_factory=list)


def _build_classifier(seed: int = 26159) -> RandomForestClassifier:
    return RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1,
    )


def cross_validate(ds: GeneratedDataset, n_splits: int = 5) -> TrainingReport:
    from sklearn.metrics import accuracy_score, f1_score

    X = np.asarray(ds.X, dtype=float)
    y = np.asarray(ds.y)
    groups = np.asarray(ds.groups)
    masked = np.asarray(ds.cert_masked) if ds.cert_masked else np.zeros(len(y), bool)

    n_groups = len(set(ds.groups))
    n_splits = max(2, min(n_splits, n_groups))
    gkf = GroupKFold(n_splits=n_splits)

    f1s: list[float] = []
    accs: list[float] = []
    all_true: list[str] = []
    all_pred: list[str] = []
    all_masked: list[bool] = []

    for train_idx, test_idx in gkf.split(X, y, groups):
        # A fold can miss a class entirely when whole configurations are held
        # out; that is the honest consequence of grouping and we keep it.
        clf = _build_classifier()
        clf.fit(X[train_idx], y[train_idx])
        pred = clf.predict(X[test_idx])

        f1s.append(f1_score(y[test_idx], pred, average="macro", zero_division=0))
        accs.append(accuracy_score(y[test_idx], pred))
        all_true.extend(y[test_idx].tolist())
        all_pred.extend(pred.tolist())
        all_masked.extend(masked[test_idx].tolist())

    labels = [c for c in CLASSES if c in set(all_true) | set(all_pred)]
    rep = classification_report(
        all_true, all_pred, labels=labels, output_dict=True, zero_division=0
    )
    cm = confusion_matrix(all_true, all_pred, labels=labels).tolist()

    # The split that carries the argument: how well the model does when the
    # certificate was readable versus when TLS 1.3 hid it.  The masked figure
    # is the one that matters, because that is the population on which the
    # rule engine has to abstain.
    t = np.asarray(all_true)
    pr = np.asarray(all_pred)
    mk = np.asarray(all_masked, dtype=bool)
    visibility: dict[str, float] = {}
    # Majority-class baselines make the lift explicit rather than implied.
    def _majority_acc(truth):
        if len(truth) == 0:
            return 0.0
        vals, counts = np.unique(truth, return_counts=True)
        return round(float(counts.max() / counts.sum()), 4)
    visibility["baseline_overall"] = _majority_acc(np.asarray(all_true))
    if mk.any():
        visibility["cert_masked_accuracy"] = round(float(accuracy_score(t[mk], pr[mk])), 4)
        visibility["cert_masked_macro_f1"] = round(
            float(f1_score(t[mk], pr[mk], average="macro", zero_division=0)), 4
        )
        visibility["cert_masked_samples"] = int(mk.sum())
        visibility["cert_masked_baseline"] = _majority_acc(t[mk])
    if (~mk).any():
        visibility["cert_visible_accuracy"] = round(float(accuracy_score(t[~mk], pr[~mk])), 4)
        visibility["cert_visible_macro_f1"] = round(
            float(f1_score(t[~mk], pr[~mk], average="macro", zero_division=0)), 4
        )
        visibility["cert_visible_samples"] = int((~mk).sum())
        visibility["cert_visible_baseline"] = _majority_acc(t[~mk])

    return TrainingReport(
        by_certificate_visibility=visibility,
        n_samples=len(ds.X),
        n_features=X.shape[1],
        n_groups=n_groups,
        classes=labels,
        cv_folds=n_splits,
        macro_f1_mean=round(float(np.mean(f1s)), 4),
        macro_f1_std=round(float(np.std(f1s)), 4),
        accuracy_mean=round(float(np.mean(accs)), 4),
        per_class={
            k: {m: round(float(v), 4) for m, v in val.items()}
            for k, val in rep.items()
            if isinstance(val, dict)
        },
        confusion=cm,
        notes=[
            "GroupKFold by server configuration profile: no session from a "
            "profile appears in both train and test.",
            "Labels come from the generating server configuration, never from "
            "the rule engine, so the model is not a re-implementation of it.",
        ],
    )


def train_and_save(
    artifact_dir: str = DEFAULT_ARTIFACT_DIR,
    n_profiles: int = 260,
    sessions_per_profile: int = 8,
    tls13_mask_rate: float = 0.30,
    seed: int = 26159,
    dataset_path: str = None,
) -> TrainingReport:
    import joblib

    os.makedirs(artifact_dir, exist_ok=True)
    ds = generate(
        n_profiles=n_profiles,
        sessions_per_profile=sessions_per_profile,
        tls13_mask_rate=tls13_mask_rate,
        seed=seed,
    )
    captured_rows = None
    if dataset_path:
        from .captured_dataset import load
        ds, captured_rows = load(dataset_path)
        if set(ds.y) != set(CLASSES):
            raise ValueError("Candidate training requires all four posture classes; extend the capture lab first")
    report = cross_validate(ds)
    if captured_rows:
        from sklearn.metrics import classification_report
        from ..assessment import digest
        comparison = classification_report(ds.y, [r['rules_baseline_class'] for r in captured_rows], output_dict=True, zero_division=0)
        with open(os.path.join(artifact_dir, 'dataset_evaluation.json'), 'w', encoding='utf-8') as fh:
            json.dump({'dataset_sha256': digest(dataset_path), 'source': 'captured_traffic',
                       'groups': len(set(ds.groups)), 'rules_only_baseline': comparison,
                       'note': 'Labels come from lab configuration. Rules baseline maps critical/high/medium-or-low/none to critical/vulnerable/weak/secure; inspect this mapping before comparing.',
                       'promotion': 'candidate_only; manually review false negatives and unseen-server validation before deployment'}, fh, indent=2)
        report.notes.append('Features extracted by the real PCAP pipeline; labels supplied by independent lab configuration.')
    report.tls13_masked_fraction = sum(ds.cert_masked) / len(ds.cert_masked) if captured_rows else tls13_mask_rate

    X = np.asarray(ds.X, dtype=float)
    y = np.asarray(ds.y)

    clf = _build_classifier(seed)
    clf.fit(X, y)

    iso = IsolationForest(
        n_estimators=200, contamination=0.12, random_state=seed, n_jobs=-1
    )
    iso.fit(X)

    report.feature_importance = {
        name: round(float(v), 5)
        for name, v in sorted(
            zip(FEATURE_NAMES, clf.feature_importances_),
            key=lambda kv: -kv[1],
        )
    }

    import sklearn

    joblib.dump(
        {
            "classifier": clf,
            "isolation": iso,
            "feature_names": list(FEATURE_NAMES),
            "classes": list(clf.classes_),
            "model_version": MODEL_VERSION,
            # Recorded so a mismatch can be detected at load time. scikit-learn
            # pickles are not portable across versions: loading one raises
            # InconsistentVersionWarning at best and fails outright at worst.
            "sklearn_version": sklearn.__version__,
        },
        os.path.join(artifact_dir, "posture_model.joblib"),
    )
    with open(os.path.join(artifact_dir, "training_report.json"), "w", encoding="utf-8") as fh:
        json.dump(asdict(report), fh, indent=2)
    return report


def main() -> None:  # pragma: no cover - CLI helper
    import argparse

    ap = argparse.ArgumentParser(description="Train the MailSentinel posture model")
    ap.add_argument("--artifacts", default=DEFAULT_ARTIFACT_DIR)
    ap.add_argument("--dataset", help="Captured-session JSONL; writes a candidate to --artifacts, never auto-promotes")
    ap.add_argument("--profiles", type=int, default=260)
    ap.add_argument("--sessions-per-profile", type=int, default=8)
    ap.add_argument("--tls13-mask-rate", type=float, default=0.30)
    ap.add_argument("--seed", type=int, default=26159)
    args = ap.parse_args()

    if args.dataset and os.path.abspath(args.artifacts) == os.path.abspath(DEFAULT_ARTIFACT_DIR):
        ap.error('For captured training, choose a separate --artifacts candidate directory')
    rep = train_and_save(
        args.artifacts, args.profiles, args.sessions_per_profile,
        args.tls13_mask_rate, args.seed, dataset_path=args.dataset
    )
    print(f"samples={rep.n_samples}  groups={rep.n_groups}  folds={rep.cv_folds}")
    print(f"macro-F1 {rep.macro_f1_mean:.4f} +/- {rep.macro_f1_std:.4f}   "
          f"accuracy {rep.accuracy_mean:.4f}")
    print("\nper class:")
    for cls in rep.classes:
        m = rep.per_class.get(cls, {})
        print(f"  {cls:12s} precision={m.get('precision', 0):.3f} "
              f"recall={m.get('recall', 0):.3f} f1={m.get('f1-score', 0):.3f} "
              f"support={int(m.get('support', 0))}")
    if rep.by_certificate_visibility:
        v = rep.by_certificate_visibility
        print("\nby certificate visibility (the split that carries the argument):")
        print(f"  cert visible  acc={v.get('cert_visible_accuracy', 0):.3f} "
              f"(baseline {v.get('cert_visible_baseline', 0):.3f}) "
              f"macroF1={v.get('cert_visible_macro_f1', 0):.3f} "
              f"n={v.get('cert_visible_samples', 0)}")
        print(f"  cert masked   acc={v.get('cert_masked_accuracy', 0):.3f} "
              f"(baseline {v.get('cert_masked_baseline', 0):.3f}) "
              f"macroF1={v.get('cert_masked_macro_f1', 0):.3f} "
              f"n={v.get('cert_masked_samples', 0)}   <- TLS 1.3; rules abstain here")
    print("\ntop features:")
    for name, imp in list(rep.feature_importance.items())[:8]:
        print(f"  {name:26s} {imp:.4f}")


if __name__ == "__main__":  # pragma: no cover
    main()
